DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS participation_request CASCADE;
DROP TABLE IF EXISTS event CASCADE;

CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name VARCHAR(250) NOT NULL,
  email VARCHAR(254) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS event (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
);

CREATE TABLE IF NOT EXISTS participation_request (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  created TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
  event_id BIGINT NOT NULL,
  requester_id BIGINT NOT NULL,
  status VARCHAR(12) NOT NULL,
  CONSTRAINT fk_event_request FOREIGN KEY (event_id) REFERENCES event(id)
        ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT fk_requester_request FOREIGN KEY (requester_id) REFERENCES users(id)
        ON UPDATE CASCADE ON DELETE CASCADE
);